using System.Text.Json;

namespace SboxNetworkStorage.Storage;

/// <summary>Exact portable row columns; JSON stored as text stays text, preserving bytes and nulls.</summary>
public static class ProjectSnapshotSchema
{
    public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, JsonValueKind>> Tables =
        new Dictionary<string, IReadOnlyDictionary<string, JsonValueKind>>(StringComparer.Ordinal)
        {
            ["projects"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["workspace_id"] = JsonValueKind.String, ["storage_owner_user_id"] = JsonValueKind.String, ["payload_json"] = JsonValueKind.String, ["version"] = JsonValueKind.Number, ["updated_at_unix_ms"] = JsonValueKind.Number },
            ["collections"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["collection_id"] = JsonValueKind.String, ["name"] = JsonValueKind.String, ["visibility"] = JsonValueKind.String, ["definition_json"] = JsonValueKind.String, ["version"] = JsonValueKind.Number, ["updated_at_unix_ms"] = JsonValueKind.Number },
            ["endpoints"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["endpoint_id"] = JsonValueKind.String, ["slug"] = JsonValueKind.String, ["method"] = JsonValueKind.String, ["enabled"] = JsonValueKind.True, ["definition_json"] = JsonValueKind.String, ["version_hash"] = JsonValueKind.String, ["version"] = JsonValueKind.Number, ["updated_at_unix_ms"] = JsonValueKind.Number },
            ["workflows"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["workflow_id"] = JsonValueKind.String, ["name"] = JsonValueKind.String, ["definition_json"] = JsonValueKind.String, ["version_hash"] = JsonValueKind.String, ["version"] = JsonValueKind.Number, ["updated_at_unix_ms"] = JsonValueKind.Number },
            ["game_values"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["payload_json"] = JsonValueKind.String, ["version_hash"] = JsonValueKind.String, ["version"] = JsonValueKind.Number, ["updated_at_unix_ms"] = JsonValueKind.Number },
            ["rate_limit_rules"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["rules_json"] = JsonValueKind.String, ["version"] = JsonValueKind.Number, ["updated_at_unix_ms"] = JsonValueKind.Number },
            ["queries"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["query_id"] = JsonValueKind.String, ["name"] = JsonValueKind.String, ["requires_secret_key"] = JsonValueKind.True, ["definition_json"] = JsonValueKind.String, ["version"] = JsonValueKind.Number, ["updated_at_unix_ms"] = JsonValueKind.Number },
            ["query_last_run"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["query_id"] = JsonValueKind.String, ["run_at"] = JsonValueKind.String, ["duration_ms"] = JsonValueKind.Number, ["keys_scanned"] = JsonValueKind.Number, ["records_returned"] = JsonValueKind.Number, ["from_cache"] = JsonValueKind.True, ["updated_at_unix_ms"] = JsonValueKind.Number },
            ["query_run_logs"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["query_id"] = JsonValueKind.String, ["created_at_unix_ms"] = JsonValueKind.Number, ["log_type"] = JsonValueKind.String, ["duration_ms"] = JsonValueKind.Number, ["keys_scanned"] = JsonValueKind.Number, ["records_returned"] = JsonValueKind.Number, ["from_cache"] = JsonValueKind.True, ["changes_json"] = JsonValueKind.String },
            ["records"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["collection_id"] = JsonValueKind.String, ["record_key"] = JsonValueKind.String, ["payload_json"] = JsonValueKind.String, ["deleted"] = JsonValueKind.True, ["version"] = JsonValueKind.Number, ["updated_at_unix_ms"] = JsonValueKind.Number },
            ["record_idempotency"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["collection_id"] = JsonValueKind.String, ["record_key"] = JsonValueKind.String, ["idempotency_key"] = JsonValueKind.String, ["result_record_version"] = JsonValueKind.Number, ["result_hash"] = JsonValueKind.String, ["payload_json"] = JsonValueKind.String, ["created_at_unix_ms"] = JsonValueKind.Number },
            ["global_records"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["collection_id"] = JsonValueKind.String, ["record_id"] = JsonValueKind.String, ["payload_json"] = JsonValueKind.String, ["version"] = JsonValueKind.Number, ["created_at_unix_ms"] = JsonValueKind.Number },
            ["ledger_entries"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["collection_id"] = JsonValueKind.String, ["record_key"] = JsonValueKind.String, ["sequence"] = JsonValueKind.Number, ["entry_json"] = JsonValueKind.String, ["created_at_unix_ms"] = JsonValueKind.Number },
            ["checkpoint_cursor"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["latest_sequence"] = JsonValueKind.Number, ["manifest_path"] = JsonValueKind.String, ["updated_at_unix_ms"] = JsonValueKind.Number, ["version"] = JsonValueKind.Number },
            ["api_keys"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["api_key"] = JsonValueKind.String, ["user_id"] = JsonValueKind.String, ["key_type"] = JsonValueKind.String, ["key_hash"] = JsonValueKind.String, ["key_identifier"] = JsonValueKind.String, ["label"] = JsonValueKind.String, ["enabled"] = JsonValueKind.True, ["permissions_json"] = JsonValueKind.String, ["version"] = JsonValueKind.Number, ["updated_at_unix_ms"] = JsonValueKind.Number },
            ["project_audit_logs"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["created_at_unix_ms"] = JsonValueKind.Number, ["log_id"] = JsonValueKind.String, ["user_id"] = JsonValueKind.String, ["action"] = JsonValueKind.String, ["actor_json"] = JsonValueKind.String, ["target_json"] = JsonValueKind.String, ["summary_json"] = JsonValueKind.String, ["diff_json"] = JsonValueKind.String },
            ["player_analytics"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["collection_id"] = JsonValueKind.String, ["record_key"] = JsonValueKind.String, ["created_at_unix_ms"] = JsonValueKind.Number, ["event_id"] = JsonValueKind.String, ["event_type"] = JsonValueKind.String, ["payload_json"] = JsonValueKind.String },
            ["player_analytics_events"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["steam_id"] = JsonValueKind.String, ["created_at_unix_ms"] = JsonValueKind.Number, ["event_id"] = JsonValueKind.String, ["event_type"] = JsonValueKind.String, ["category"] = JsonValueKind.String, ["label"] = JsonValueKind.String, ["endpoint_slug"] = JsonValueKind.String, ["collection_id"] = JsonValueKind.String, ["payload_json"] = JsonValueKind.String },
            ["player_profiles"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["steam_id"] = JsonValueKind.String, ["player_name"] = JsonValueKind.String, ["is_online"] = JsonValueKind.True, ["online_since_unix_ms"] = JsonValueKind.Number, ["last_seen_unix_ms"] = JsonValueKind.Number, ["last_heartbeat_unix_ms"] = JsonValueKind.Number, ["current_session_id"] = JsonValueKind.String, ["current_session_last_seconds"] = JsonValueKind.Number, ["total_seconds"] = JsonValueKind.Number, ["session_count"] = JsonValueKind.Number, ["last_event_type"] = JsonValueKind.String, ["last_endpoint_slug"] = JsonValueKind.String, ["managed_counters_json"] = JsonValueKind.String, ["updated_at_unix_ms"] = JsonValueKind.Number },
            ["player_sessions"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["steam_id"] = JsonValueKind.String, ["session_id"] = JsonValueKind.String, ["started_at_unix_ms"] = JsonValueKind.Number, ["last_heartbeat_at_unix_ms"] = JsonValueKind.Number, ["ended_at_unix_ms"] = JsonValueKind.Number, ["last_metrics_json"] = JsonValueKind.String, ["summary_json"] = JsonValueKind.String },
            ["project_analytics_issues"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["bucket_date"] = JsonValueKind.String, ["created_at_unix_ms"] = JsonValueKind.Number, ["event_id"] = JsonValueKind.String, ["steam_id"] = JsonValueKind.String, ["category"] = JsonValueKind.String, ["event_type"] = JsonValueKind.String, ["label"] = JsonValueKind.String, ["payload_json"] = JsonValueKind.String },
            ["project_members"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["user_id"] = JsonValueKind.String, ["project_id"] = JsonValueKind.String, ["role"] = JsonValueKind.String, ["created_at_unix_ms"] = JsonValueKind.Number },
            ["pages"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["page_slug"] = JsonValueKind.String, ["title"] = JsonValueKind.String, ["content_json"] = JsonValueKind.String, ["created_at_unix_ms"] = JsonValueKind.Number, ["updated_at_unix_ms"] = JsonValueKind.Number },
            ["storage_errors"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["created_at_unix_ms"] = JsonValueKind.Number, ["error_id"] = JsonValueKind.String, ["message"] = JsonValueKind.String, ["stack_trace"] = JsonValueKind.String, ["source"] = JsonValueKind.String, ["request_path"] = JsonValueKind.String, ["severity"] = JsonValueKind.String },
            ["storage_request_log"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["created_at_unix_ms"] = JsonValueKind.Number, ["method"] = JsonValueKind.String, ["path"] = JsonValueKind.String, ["status_code"] = JsonValueKind.Number, ["duration_ms"] = JsonValueKind.Number, ["api_key_identifier"] = JsonValueKind.String },
            ["project_usage_monthly"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["month"] = JsonValueKind.String, ["requests"] = JsonValueKind.Number, ["reads"] = JsonValueKind.Number, ["writes"] = JsonValueKind.Number, ["endpoint_calls"] = JsonValueKind.Number, ["bytes_in"] = JsonValueKind.Number, ["bytes_out"] = JsonValueKind.Number, ["errors"] = JsonValueKind.Number, ["duration_ms_sum"] = JsonValueKind.Number, ["duration_samples"] = JsonValueKind.Number, ["compute_units"] = JsonValueKind.Number, ["storage_delta_bytes"] = JsonValueKind.Number },
            ["project_usage_daily"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["month"] = JsonValueKind.String, ["day"] = JsonValueKind.String, ["requests"] = JsonValueKind.Number, ["bytes_in"] = JsonValueKind.Number, ["bytes_out"] = JsonValueKind.Number, ["errors"] = JsonValueKind.Number, ["compute_units"] = JsonValueKind.Number },
            ["project_usage_endpoints"] = new Dictionary<string, JsonValueKind>(StringComparer.Ordinal) { ["project_id"] = JsonValueKind.String, ["month"] = JsonValueKind.String, ["endpoint_slug"] = JsonValueKind.String, ["calls"] = JsonValueKind.Number, ["errors"] = JsonValueKind.Number, ["duration_ms_sum"] = JsonValueKind.Number, ["compute_units"] = JsonValueKind.Number },
        };

    public static void Validate(string projectId, string table, JsonElement row)
    {
        if (!Tables.TryGetValue(table, out var columns) || row.ValueKind != JsonValueKind.Object)
            throw new InvalidOperationException("Unknown snapshot table or invalid row.");
        var names = row.EnumerateObject().Select(p => p.Name).ToArray();
        if (names.Length != columns.Count || names.Distinct(StringComparer.Ordinal).Count() != names.Length || names.Any(n => !columns.ContainsKey(n)))
            throw new InvalidOperationException("Snapshot row columns do not exactly match the portable schema.");
        if (row.GetProperty("project_id").GetString() != projectId) throw new InvalidOperationException("Cross-project snapshot row.");
        foreach (var column in columns)
        {
            var value = row.GetProperty(column.Key);
            if (value.ValueKind == JsonValueKind.Null) continue;
            if (column.Value == JsonValueKind.True && value.ValueKind == JsonValueKind.False) continue;
            if (value.ValueKind != column.Value) throw new InvalidOperationException("Snapshot column type mismatch.");
            if (value.ValueKind == JsonValueKind.Number) _ = value.GetInt64();
        }
    }
}
