#!/bin/sh
# sbox Network Storage Server installer for Linux and macOS.
#
#   curl -fsSL https://github.com/sbox-cool/sbox-network-storage-server/releases/latest/download/install.sh | sh
#
# One line from a fresh VPS to a running server with a project and keys:
#
#   curl -fsSL https://github.com/sbox-cool/sbox-network-storage-server/releases/latest/download/install.sh | SBOX_NS_PROJECT="My Game" sh
#
# Environment variables:
#   SBOX_NS_PROJECT      Configure non-interactively (SQLite), create or reuse this project with
#                        public and secret keys, and print the line to add to your game.
#   SBOX_NS_PUBLIC_URL   Address players use, e.g. https://ns.example.com (used with SBOX_NS_PROJECT).
#   SBOX_NS_TUNNEL       Set to 1 for a hosted HTTPS name after quickstart/setup and before service start.
#   SBOX_NS_DNS          Set to 1 for a signed DNS name pointing directly to your public IP.
#                        Requires a running systemd service, public HTTP/443 ports, and the two
#                        Let's Encrypt variables below. Registration happens after service start.
#   SBOX_NS_ACME_EMAIL   Certificate contact email for SBOX_NS_DNS=1.
#   SBOX_NS_ACCEPT_LETSENCRYPT_TERMS Set to 1 to accept the Let's Encrypt subscriber agreement.
#   SBOX_NS_TELEMETRY    Set to 1 to opt in to anonymous usage statistics after quickstart/setup
#                        (off by default; preview with `sbox-ns telemetry preview`).
#   SBOX_NS_VERSION      Install this version (for example 0.3.0 or v0.3.0) instead of the latest release.
#   SBOX_NS_PRERELEASE   Set to 1 to resolve the newest release including prereleases.
#   SBOX_NS_CHANNEL      Release channel: stable or canary. Without SBOX_NS_VERSION the version comes from
#                        the sboxcool.com release feed for that channel (GitHub latest if the feed is down),
#                        and updates.channel is set in the configuration.
#   SBOX_NS_AUTO_UPDATE  Set to 1 to install the sbox-ns-update timer with the service and set
#                        updates.auto_install = true (Linux with systemd, as root). Off by default.
#   SBOX_NS_NO_SETUP     Set to 1 to skip running `sbox-ns setup`.
#   SBOX_NS_NO_SERVICE   Set to 1 to skip `sbox-ns service install` on systemd hosts.
#   SBOX_NS_INSECURE_SKIP_SIGNATURE Set to 1 ONLY for a manual install without signature verification.
#                        DANGEROUS: archive hashes alone do not authenticate a release.
#   GITHUB_TOKEN         Optional token used for GitHub API requests (avoids rate limits).
#
# Options:
#   --print-platform     Print the detected release platform (for example linux-x64) and exit.
#
# Licensed under AGPL-3.0-only. https://github.com/sbox-cool/sbox-network-storage-server

set -eu

REPO="sbox-cool/sbox-network-storage-server"
BIN_NAME="sbox-ns"
SERVICE_USER="sbox-ns"
LINUX_CONFIG_DIR="/etc/sbox-ns"
LINUX_DATA_DIR="/var/lib/sbox-ns"
FEED_URL="https://sboxcool.com/api/network-storage/releases/latest"

# BEGIN PINNED RELEASE KEYS (generated by scripts/pin-release-keys.sh)
PINNED_RELEASE_KEYS='-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAExfYmy6yAOb5bRmkZN7D4Z97aH+Zg
sUwT8DH9R9CrDEr+7Cn3y5PddKFlcf0Sx+5a3Ap/fqvhOlRTGSqkEzLw7g==
-----END PUBLIC KEY-----
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEgz9uz00EZ6FpZYXZUgWDsSQkENtd
+dxeL1p0ICLZko6RTnEg0lziHLChCFuk/lrwjbZX7nMQuqtyeArf9aEseg==
-----END PUBLIC KEY-----'
# END PINNED RELEASE KEYS

say() {
    printf '%s\n' "$*"
}

warn() {
    printf 'warning: %s\n' "$*" >&2
}

die() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

has() {
    command -v "$1" >/dev/null 2>&1
}

# Maps an OS name ($1, as from `uname -s`) and CPU name ($2, as from `uname -m`)
# to a release platform identifier such as linux-x64 or osx-arm64.
detect_platform() {
    case "$1" in
        Linux | linux) _os="linux" ;;
        Darwin | darwin) _os="osx" ;;
        *) die "unsupported operating system: $1 (use the Docker image, or install.ps1 on Windows)" ;;
    esac

    case "$2" in
        x86_64 | amd64 | x64) _arch="x64" ;;
        aarch64 | arm64 | armv8*) _arch="arm64" ;;
        *) die "unsupported CPU architecture: $2 (supported: x64, arm64)" ;;
    esac

    printf '%s-%s\n' "$_os" "$_arch"
}

# Prints the release platform identifier for this machine.
host_platform() {
    _platform="$(detect_platform "$(uname -s)" "$(uname -m)")"
    # Rosetta 2 reports x86_64 for translated shells on Apple Silicon; prefer the native build.
    if [ "$_platform" = "osx-x64" ] && [ "$(sysctl -in sysctl.proc_translated 2>/dev/null || echo 0)" = "1" ]; then
        _platform="osx-arm64"
    fi
    printf '%s\n' "$_platform"
}

http_get() {
    # $1 = url, $2 = output file ("-" for stdout)
    if has curl; then
        if [ -n "${GITHUB_TOKEN:-}" ] && case "$1" in https://api.github.com/*) true ;; *) false ;; esac; then
            curl -fsSL --proto '=https' --proto-redir '=https' --tlsv1.2 -H "Authorization: Bearer $GITHUB_TOKEN" -o "$2" "$1"
        else
            curl -fsSL --proto '=https' --proto-redir '=https' --tlsv1.2 -o "$2" "$1"
        fi
    elif has wget; then
        if [ -n "${GITHUB_TOKEN:-}" ] && case "$1" in https://api.github.com/*) true ;; *) false ;; esac; then
            wget -q --https-only --header="Authorization: Bearer $GITHUB_TOKEN" -O "$2" "$1"
        else
            wget -q --https-only -O "$2" "$1"
        fi
    else
        die "curl or wget is required"
    fi
}

resolve_version() {
    if [ -n "${SBOX_NS_VERSION:-}" ]; then
        printf '%s\n' "${SBOX_NS_VERSION#v}"
        return
    fi

    if [ -n "${SBOX_NS_CHANNEL:-}" ] && [ "${SBOX_NS_PRERELEASE:-0}" != "1" ]; then
        _version="$(http_get "$FEED_URL?channel=$SBOX_NS_CHANNEL" - 2>/dev/null | sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')" || _version=""
        if [ -n "$_version" ]; then
            printf '%s\n' "${_version#v}"
            return
        fi
        warn "release feed unavailable for channel $SBOX_NS_CHANNEL; using the latest GitHub release"
    fi

    if [ "${SBOX_NS_PRERELEASE:-0}" = "1" ]; then
        _url="https://api.github.com/repos/$REPO/releases?per_page=1"
    else
        _url="https://api.github.com/repos/$REPO/releases/latest"
    fi

    _tag="$(http_get "$_url" - | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')"
    [ -n "$_tag" ] || die "could not resolve the latest release from $_url (set SBOX_NS_VERSION to pick one)"
    printf '%s\n' "${_tag#v}"
}

validate_version() {
    case "$1" in
        *'
'*) die "invalid release version; refusing to construct download URLs" ;;
    esac
    printf '%s\n' "$1" | LC_ALL=C grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$' \
        || die "invalid release version '$1'; refusing to construct download URLs"
}

signature_preflight() {
    if [ "${SBOX_NS_INSECURE_SKIP_SIGNATURE:-0}" = "1" ]; then
        [ "${SBOX_NS_AUTO_UPDATE:-0}" != "1" ] \
            || die "SBOX_NS_INSECURE_SKIP_SIGNATURE=1 is forbidden with unattended updates"
        warn "DANGER: SBOX_NS_INSECURE_SKIP_SIGNATURE=1 disables release authentication for this manual install!"
        return
    fi
    has openssl || die "openssl is required to authenticate releases. Install it with 'apt-get install openssl', 'dnf install openssl', or 'brew install openssl', then retry."
    [ -n "$PINNED_RELEASE_KEYS" ] \
        || die "no pinned release signing keys; refusing to install. The release maintainer must supply keys and run scripts/pin-release-keys.sh."
}

verify_signature() {
    # $1 = SHA256SUMS, $2 = DER signature, $3 = private temporary directory
    [ "${SBOX_NS_INSECURE_SKIP_SIGNATURE:-0}" != "1" ] || return 0
    mkdir "$3/keys"
    printf '%s\n' "$PINNED_RELEASE_KEYS" | awk -v dir="$3/keys" '
        /-----BEGIN PUBLIC KEY-----/ { n++; file = dir "/" n ".pem" }
        file != "" { print > file }
        /-----END PUBLIC KEY-----/ { close(file); file = "" }
    '
    for key in "$3"/keys/*.pem; do
        [ -f "$key" ] || continue
        if openssl dgst -sha256 -verify "$key" -signature "$2" "$1" >/dev/null 2>&1; then
            say "Pinned P-256 signature verified."
            return
        fi
    done
    die "signature verification of SHA256SUMS failed; refusing to install"
}

sha256_of() {
    if has sha256sum; then
        sha256sum "$1" | cut -d ' ' -f 1
    elif has shasum; then
        shasum -a 256 "$1" | cut -d ' ' -f 1
    else
        die "sha256sum or shasum is required to verify the download"
    fi
}

verify_checksum() {
    # $1 = archive path, $2 = SHA256SUMS path, $3 = archive file name
    _expected="$(awk -v f="$3" '{ name = $2; sub(/^\*/, "", name); if (name == f) { print $1; exit } }' "$2")"
    [ -n "$_expected" ] || die "$3 is not listed in SHA256SUMS; refusing to install"
    _actual="$(sha256_of "$1")"
    if [ "$_expected" != "$_actual" ]; then
        die "checksum mismatch for $3 (expected $_expected, got $_actual); refusing to install"
    fi
    say "Checksum verified: $_actual"
}

is_root() {
    [ "$(id -u)" -eq 0 ]
}

has_systemd() {
    [ -d /run/systemd/system ] && has systemctl
}

has_tty() {
    [ -t 1 ] && { : </dev/tty; } 2>/dev/null
}

ensure_service_user() {
    if id "$SERVICE_USER" >/dev/null 2>&1; then
        return
    fi
    say "Creating system user '$SERVICE_USER'"
    if has systemd-sysusers; then
        mkdir -p /usr/lib/sysusers.d
        # Same snippet as install/sbox-ns.sysusers.conf; the installer is standalone.
        printf '%s\n' 'u sbox-ns - "sbox Network Storage Server" /var/lib/sbox-ns /usr/sbin/nologin' \
            > /usr/lib/sysusers.d/sbox-ns.conf
        systemd-sysusers /usr/lib/sysusers.d/sbox-ns.conf
    elif has useradd; then
        useradd --system --user-group --home-dir "$LINUX_DATA_DIR" --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
    elif has adduser; then
        # BusyBox / Alpine
        adduser -S -D -H -h "$LINUX_DATA_DIR" -s /sbin/nologin "$SERVICE_USER"
    else
        die "cannot create user '$SERVICE_USER': neither useradd nor adduser is available"
    fi
}

secure_operator_config() {
    # Never transfer operator configuration to the runtime account.
    find "$config_dir" -type d -exec chown "root:$SERVICE_USER" {} + -exec chmod 0750 {} +
    find "$config_dir" -type f -exec chown "root:$SERVICE_USER" {} + -exec chmod 0640 {} +
}

runtime_command() {
    if [ "$service_layout" -eq 1 ]; then
        runuser -u "$SERVICE_USER" -- "$ns" "$@"
    else
        "$ns" "$@"
    fi
}

rewrite_game_url() {
    # Keep secret-key output, but replace the buffered quickstart URL.
    game_url_suffix='", "*'
    while IFS= read -r line; do
        case "$line" in
            *NetworkStorage.Configure*) printf '%s", "%s" );\n' "${line%$game_url_suffix}" "$1" ;;
            "Replace <this-host>"*|"    sbox-ns config set server.public_url"*) ;;
            *) printf '%s\n' "$line" ;;
        esac
    done
}

main() {
    if [ "${1:-}" = "--print-platform" ]; then
        host_platform
        return
    fi

    case "${SBOX_NS_CHANNEL:-stable}" in
        stable | canary) ;;
        *) die "SBOX_NS_CHANNEL must be stable or canary (got '$SBOX_NS_CHANNEL')" ;;
    esac
    if [ "${SBOX_NS_DNS:-0}" = "1" ]; then
        [ "${SBOX_NS_TUNNEL:-0}" != "1" ] || die "SBOX_NS_DNS and SBOX_NS_TUNNEL cannot both be enabled."
        [ -n "${SBOX_NS_ACME_EMAIL:-}" ] && [ "${SBOX_NS_ACCEPT_LETSENCRYPT_TERMS:-0}" = "1" ] \
            || die "SBOX_NS_DNS=1 requires SBOX_NS_ACME_EMAIL and SBOX_NS_ACCEPT_LETSENCRYPT_TERMS=1."
        is_root && has_systemd && [ "${SBOX_NS_NO_SERVICE:-0}" != "1" ] \
            || die "SBOX_NS_DNS=1 requires root and the systemd service; otherwise start the server and run 'sbox-ns dns enable' manually."
    fi
    say "Optional hosted dependencies: signed DNS registration and IP updates require the sboxcool registry."
    say "Existing DNS names resolve via Bunny; player traffic goes directly to your server, not through a tunnel."
    say "Tunnel traffic uses Cloudflare. These optional services have no reliability guarantee."

    platform="$(host_platform)"
    os="${platform%%-*}"
    version="$(resolve_version)"
    validate_version "$version"
    signature_preflight
    archive="$BIN_NAME-$version-$platform.tar.gz"
    base_url="https://github.com/$REPO/releases/download/v$version"

    # Choose the install layout.
    #   Linux as root:  /usr/local/bin/sbox-ns, config /etc/sbox-ns, data /var/lib/sbox-ns, systemd service.
    #   Otherwise:      <install dir>/sbox-ns with config/ and data/ beside it, linked into a bin dir on PATH.
    service_layout=0
    if is_root; then
        bin_dir="/usr/local/bin"
        if [ "$os" = "linux" ]; then
            service_layout=1
            install_dir="$bin_dir"
            config_dir="$LINUX_CONFIG_DIR"
            data_dir="$LINUX_DATA_DIR"
        else
            install_dir="/opt/sbox-ns"
            config_dir="$install_dir/config"
            data_dir="$install_dir/data"
        fi
    else
        bin_dir="$HOME/.local/bin"
        install_dir="${XDG_DATA_HOME:-$HOME/.local/share}/sbox-ns"
        config_dir="$install_dir/config"
        data_dir="$install_dir/data"
    fi

    say "Installing sbox Network Storage Server $version ($platform)"

    tmp="$(mktemp -d 2>/dev/null || mktemp -d -t sbox-ns)"
    trap 'rm -rf "$tmp"' EXIT INT TERM

    say "Downloading $archive"
    http_get "$base_url/$archive" "$tmp/$archive" || die "download failed: $base_url/$archive"
    http_get "$base_url/SHA256SUMS" "$tmp/SHA256SUMS" || die "download failed: $base_url/SHA256SUMS"
    if [ "${SBOX_NS_INSECURE_SKIP_SIGNATURE:-0}" != "1" ]; then
        http_get "$base_url/SHA256SUMS.p256.sig" "$tmp/SHA256SUMS.p256.sig" \
            || die "missing or unavailable SHA256SUMS.p256.sig; refusing to install"
        verify_signature "$tmp/SHA256SUMS" "$tmp/SHA256SUMS.p256.sig" "$tmp"
    fi
    verify_checksum "$tmp/$archive" "$tmp/SHA256SUMS" "$archive"

    mkdir -p "$tmp/extract"
    tar -xzf "$tmp/$archive" -C "$tmp/extract"
    [ -f "$tmp/extract/$BIN_NAME" ] || die "archive does not contain $BIN_NAME"

    if [ "$service_layout" -eq 1 ]; then
        has runuser || die "runuser is required for Linux service installs (install util-linux)"
        ensure_service_user
    fi

    mkdir -p "$install_dir" "$bin_dir"
    # Install via a temporary name and rename, so a running binary is replaced atomically.
    cp "$tmp/extract/$BIN_NAME" "$install_dir/.$BIN_NAME.new"
    chmod 0755 "$install_dir/.$BIN_NAME.new"
    mv -f "$install_dir/.$BIN_NAME.new" "$install_dir/$BIN_NAME"
    if [ "$install_dir" != "$bin_dir" ]; then
        ln -sf "$install_dir/$BIN_NAME" "$bin_dir/$BIN_NAME"
    fi
    if [ "$os" = "osx" ] && has xattr; then
        xattr -d com.apple.quarantine "$install_dir/$BIN_NAME" 2>/dev/null || true
    fi
    say "Installed $bin_dir/$BIN_NAME"

    if [ "$service_layout" -eq 1 ] && { [ -d "$config_dir" ] || [ -d "$data_dir" ]; } \
        && [ ! -f "$data_dir/state/.layout-version" ]; then
        # v0.4.0 lacks this command. Use the authenticated installed binary, not
        # a temporary path that migration would embed into the restarted units.
        say "Migrating the existing Linux layout before setup or service installation..."
        "$install_dir/$BIN_NAME" layout migrate --config-dir "$config_dir" --data-dir "$data_dir" \
            || die "layout migration failed; no setup or service installation was attempted"
    fi

    if [ "$service_layout" -eq 1 ]; then
        umask 0027
        install -d -o root -g "$SERVICE_USER" -m 0750 "$config_dir"
        install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 "$data_dir" \
            "$data_dir/state" "$data_dir/state/secrets" "$data_dir/state/conf.d" "$data_dir/state/bin"
        secure_operator_config
    else
        mkdir -p "$config_dir" "$data_dir"
    fi

    ns="$install_dir/$BIN_NAME"
    dirs="--config-dir $config_dir --data-dir $data_dir"
    setup_cmd="$BIN_NAME setup $dirs"
    if [ "$service_layout" -eq 1 ]; then
        setup_cmd="sudo $setup_cmd"
    fi

    quickstart_out=""
    if [ -n "${SBOX_NS_PROJECT:-}" ]; then
        say ""
        say "Configuring the server and creating project \"$SBOX_NS_PROJECT\"..."
        # quickstart configures non-interactively when no config exists and is safe to re-run.
        if [ -n "${SBOX_NS_PUBLIC_URL:-}" ]; then
            # shellcheck disable=SC2086 # $dirs is intentionally split into flags
            quickstart_out=$("$ns" quickstart "$SBOX_NS_PROJECT" $dirs --public-url "$SBOX_NS_PUBLIC_URL") || die "quickstart failed; rerun: $BIN_NAME quickstart \"$SBOX_NS_PROJECT\" $dirs"
        else
            # shellcheck disable=SC2086 # $dirs is intentionally split into flags
            quickstart_out=$("$ns" quickstart "$SBOX_NS_PROJECT" $dirs) || die "quickstart failed; rerun: $BIN_NAME quickstart \"$SBOX_NS_PROJECT\" $dirs"
        fi
        configured=1
    elif [ -f "$config_dir/server.toml" ]; then
        say "Existing configuration found in $config_dir; keeping it."
        configured=1
    elif [ "${SBOX_NS_NO_SETUP:-0}" = "1" ]; then
        configured=0
    elif has_tty; then
        say ""
        say "Starting interactive setup..."
        # shellcheck disable=SC2086 # $dirs is intentionally split into flags
        "$ns" setup $dirs </dev/tty
        configured=1
    else
        configured=0
    fi

    if [ "$service_layout" -eq 1 ]; then
        secure_operator_config
    fi
    if [ "${SBOX_NS_TUNNEL:-0}" = "1" ]; then
        [ "$configured" -eq 1 ] || die "SBOX_NS_TUNNEL=1 requires setup or SBOX_NS_PROJECT."
        say "Enabling the verified HTTPS tunnel..."
        runtime_command tunnel enable --config-dir "$config_dir" --data-dir "$data_dir" || die "tunnel enable failed; service was not started"
        # shellcheck disable=SC2086
        tunnel_url=$("$ns" config get server.public_url $dirs) || die "cannot read tunnel public URL"
        if [ -n "$quickstart_out" ]; then
            # Preserve any newly created secret key, but replace the buffered pre-tunnel game URL.
            quickstart_out=$(printf '%s\n' "$quickstart_out" | rewrite_game_url "$tunnel_url")
        fi
    fi

    if [ "${SBOX_NS_TELEMETRY:-0}" = "1" ]; then
        [ "$configured" -eq 1 ] || die "SBOX_NS_TELEMETRY=1 requires setup or SBOX_NS_PROJECT."
        runtime_command telemetry enable --config-dir "$config_dir" --data-dir "$data_dir" || die "telemetry enable failed; service was not started"
    fi

    if [ -n "${SBOX_NS_CHANNEL:-}" ]; then
        if [ "$configured" -eq 1 ]; then
            # shellcheck disable=SC2086 # $dirs is intentionally split into flags
            "$ns" config set updates.channel "$SBOX_NS_CHANNEL" $dirs || die "could not set updates.channel"
        else
            warn "SBOX_NS_CHANNEL: no configuration yet; set it after setup with '$BIN_NAME config set updates.channel $SBOX_NS_CHANNEL $dirs'"
        fi
    fi

    auto_update_flag=""
    if [ "${SBOX_NS_AUTO_UPDATE:-0}" = "1" ]; then
        auto_update_flag="--auto-update"
    fi

    if [ "$service_layout" -eq 1 ]; then
        secure_operator_config
    fi

    service_installed=0
    service_running=0
    if [ "$service_layout" -eq 1 ] && [ "$configured" -eq 1 ] && has_systemd && [ "${SBOX_NS_NO_SERVICE:-0}" != "1" ]; then
        say "Installing systemd service"
        # shellcheck disable=SC2086 # $dirs is intentionally split into flags
        if "$ns" service install $dirs $auto_update_flag; then
            service_installed=1
            if "$ns" service start; then
                service_running=1
            else
                warn "service start failed; check '$BIN_NAME logs'"
            fi
        else
            warn "service install failed; run '$BIN_NAME service install $dirs $auto_update_flag' manually"
        fi
    fi

    if [ -n "$auto_update_flag" ] && [ "$service_installed" -ne 1 ]; then
        warn "SBOX_NS_AUTO_UPDATE=1 needs the systemd service: run '$BIN_NAME service install $dirs --auto-update'"
        warn "(or '$BIN_NAME service install --instance NAME --port PORT --auto-update' for named instances) as root"
    fi

    if [ "${SBOX_NS_DNS:-0}" = "1" ]; then
        [ "$service_running" -eq 1 ] || die "DNS registration requires the service to start successfully first."
        say "Service started. Registering the signed DNS name (the registry checks its HTTP proof)..."
        # shellcheck disable=SC2086 # $dirs is intentionally split into flags
        runtime_command dns enable --config-dir "$config_dir" --data-dir "$data_dir" --accept-letsencrypt-terms --email "$SBOX_NS_ACME_EMAIL" \
            || die "DNS registration failed; the service remains running without the new DNS configuration."
        "$ns" service restart || die "DNS configured but service restart failed; check '$BIN_NAME logs'."
        # shellcheck disable=SC2086
        dns_url=$("$ns" config get server.public_url $dirs) || die "cannot read DNS public URL"
        if [ -n "$quickstart_out" ]; then
            quickstart_out=$(printf '%s\n' "$quickstart_out" | rewrite_game_url "$dns_url")
        fi
    fi

    say ""
    say "sbox Network Storage Server $version is installed."
    say ""
    say "  Binary:  $bin_dir/$BIN_NAME"
    say "  Config:  $config_dir"
    say "  Data:    $data_dir"
    say ""
    say "Next steps:"
    _step=1
    if [ "$configured" -eq 0 ]; then
        say "  $_step. Run setup:            $setup_cmd"
        _step=$((_step + 1))
    fi
    if [ "$service_installed" -eq 1 ]; then
        say "  $_step. Check the service:    $BIN_NAME service status"
        _step=$((_step + 1))
        say "  $_step. Follow the logs:      $BIN_NAME logs -f"
        _step=$((_step + 1))
    elif [ "$service_layout" -eq 1 ] && has_systemd; then
        say "  $_step. Install the service:  $BIN_NAME service install $dirs && $BIN_NAME service start"
        _step=$((_step + 1))
    else
        say "  $_step. Start the server:     $BIN_NAME start $dirs"
        _step=$((_step + 1))
    fi
    # quickstart/setup write root-owned operator files; runtime state uses the service identity.
    as_operator=""
    if [ "$service_layout" -eq 1 ]; then
        as_operator="sudo "
    fi
    if [ -n "$quickstart_out" ]; then
        say ""
        say "$quickstart_out"
    else
        say "  $_step. Create a project and keys, and get the line for your game:"
        say "                            $as_operator$BIN_NAME quickstart \"My Game\" $dirs"
    fi

    case ":$PATH:" in
        *":$bin_dir:"*) ;;
        *)
            say ""
            warn "$bin_dir is not on your PATH. Add it, for example:"
            say "  echo 'export PATH=\"$bin_dir:\$PATH\"' >> ~/.profile"
            ;;
    esac

    say ""
    say "Docs: https://github.com/$REPO#readme"
}

main "$@"
