using System.Text.Json;
using SboxNetworkStorage.Application.NetworkStorage.Endpoints;

namespace SboxNetworkStorage.Server.Tests.NetworkStorage;

/// <summary>
/// Asserts the native <see cref="EndpointStepExecutor"/> reproduces the
/// authoritative Bun <c>executeEndpoint</c> output (ok/status/body) for every
/// deterministic-subset fixture in the golden oracle
/// (endpoint-executor-oracle.json, generated by endpoint-executor-oracle.mjs in
/// dry-run mode with mocked reads).
///
/// Success bodies are compared in full. Error bodies compare status +
/// <c>error.code</c> + <c>error.message</c> + condition-rejection metadata;
/// the diagnostic <c>error.step</c>/<c>error.docsUrl</c> fields are not part of
/// the runtime contract and are normalized out.
/// </summary>
public sealed class EndpointStepExecutorParityTests
{
    private static readonly OracleCase[] Cases = LoadOracle();
    private static readonly DateTimeOffset FixedTime = DateTimeOffset.Parse("2026-06-10T00:00:00Z");

    [Fact]
    public void OracleFixture_IsNonTrivial()
    {
        Assert.True(Cases.Length >= 15, $"Expected >=15 executor-oracle cases, found {Cases.Length}.");
        Assert.Contains(Cases, c => c.Id == "condition_reject");
        Assert.Contains(Cases, c => c.Id == "read_mock_and_echo");
    }

    [Fact]
    public void EndpointStepExecutor_MatchesJsRuntime_ForEveryOracleCase()
    {
        var executor = new EndpointStepExecutor();
        var failures = new List<string>();

        foreach (var c in Cases)
        {
            var def = (Dictionary<string, object?>)EndpointExpression.FromJson(c.Def)!;
            var input = AsDict(EndpointExpression.FromJson(c.Request.GetProperty("input")));
            var gameValues = AsDict(EndpointExpression.FromJson(c.Request.GetProperty("gameValues")));
            var steamId = c.Request.GetProperty("steamId").GetString() ?? "";
            var mock = AsDict(EndpointExpression.FromJson(c.Request.GetProperty("mockData")));

            var request = new EndpointExecutionRequest(
                Input: input,
                SteamId: steamId,
                PlayerKey: steamId,
                GameValues: gameValues,
                ProjectId: "proj_oracle",
                UserId: "user_oracle",
                HasSecretKey: false,
                IsDedicatedServer: false,
                ExecTime: FixedTime,
                ReadRecord: (collection, _) => mock.TryGetValue(collection, out var rec) ? rec : null);

            EndpointExecutionResult result;
            try
            {
                result = executor.Execute(def, request);
            }
            catch (EndpointExecutionUnsupportedException ex)
            {
                failures.Add($"[{c.Id}] unexpectedly UNSUPPORTED: {ex.Message}");
                continue;
            }

            if (result.Ok != c.Ok) { failures.Add($"[{c.Id}] ok: expected {c.Ok}, got {result.Ok}"); continue; }
            if (result.Status != c.Status) { failures.Add($"[{c.Id}] status: expected {c.Status}, got {result.Status}"); continue; }

            var expectedBody = Normalize(ConvertJson(c.Body));
            var actualBody = Normalize(result.Body);
            if (!JsDeepEquals(actualBody, expectedBody))
                failures.Add($"[{c.Id}] body: expected {Json(c.Body)} got {Json(actualBody)}");
        }

        Assert.True(failures.Count == 0, $"{failures.Count}/{Cases.Length} executor parity mismatches:\n  " + string.Join("\n  ", failures));
    }

    [Fact]
    public void Execute_UnsupportedStepType_Throws()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?> { new Dictionary<string, object?> { ["id"] = "w", ["type"] = "workflow", ["workflow"] = "some-workflow" } },
        };
        Assert.Throws<EndpointExecutionUnsupportedException>(() => executor.Execute(def, MinimalRequest()));
    }

    [Fact]
    public void Execute_RoutedFlow_Throws()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?> { new Dictionary<string, object?>
            {
                ["id"] = "c", ["type"] = "condition",
                ["check"] = new Dictionary<string, object?> { ["field"] = "input.x", ["op"] = "==", ["value"] = 1d },
                ["routes"] = new Dictionary<string, object?> { ["false"] = new Dictionary<string, object?> { ["action"] = "goto", ["step"] = "other" } },
            } },
        };
        Assert.Throws<EndpointExecutionUnsupportedException>(() => executor.Execute(def, MinimalRequest()));
    }

    [Fact]
    public void Execute_RequiredReadMissing_ReturnsNotFound()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?> { new Dictionary<string, object?>
            {
                ["id"] = "p", ["type"] = "read", ["collection"] = "players", ["key"] = "{{steamId}}", ["required"] = true,
            } },
            ["response"] = new Dictionary<string, object?> { ["status"] = 200d, ["body"] = new Dictionary<string, object?> { ["ok"] = true } },
        };
        var result = executor.Execute(def, MinimalRequest());
        Assert.False(result.Ok);
        Assert.Equal(400, result.Status);
        var error = (Dictionary<string, object?>)((Dictionary<string, object?>)result.Body!)["error"]!;
        Assert.Equal("NOT_FOUND", error["code"]);
    }

    [Fact]
    public void Execute_RandomInt_ProducesValueInRange()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?> { new Dictionary<string, object?>
            {
                ["id"] = "roll", ["type"] = "random", ["mode"] = "int", ["min"] = 1d, ["max"] = 100d,
            } },
            ["response"] = new Dictionary<string, object?> { ["status"] = 200d, ["body"] = new Dictionary<string, object?> { ["roll"] = "{{roll}}" } },
        };
        var result = executor.Execute(def, MinimalRequest());
        Assert.True(result.Ok);
        var body = (Dictionary<string, object?>)result.Body!;
        var roll = (double)body["roll"]!;
        Assert.InRange(roll, 1, 99); // [1, 100) integer
    }

    [Fact]
    public void Execute_RandomWeighted_SelectsFromItems()
    {
        var executor = new EndpointStepExecutor();
        var items = new List<object?>
        {
            new Dictionary<string, object?> { ["id"] = "common", ["weight"] = 90d },
            new Dictionary<string, object?> { ["id"] = "rare", ["weight"] = 10d },
        };
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?> { new Dictionary<string, object?>
            {
                ["id"] = "drop", ["type"] = "random", ["mode"] = "weighted", ["items"] = items, ["weightField"] = "weight",
            } },
            ["response"] = new Dictionary<string, object?> { ["status"] = 200d, ["body"] = new Dictionary<string, object?> { ["drop"] = "{{drop}}" } },
        };
        var result = executor.Execute(def, MinimalRequest());
        Assert.True(result.Ok);
        var body = (Dictionary<string, object?>)result.Body!;
        var drop = body["drop"] as Dictionary<string, object?>;
        Assert.NotNull(drop);
        Assert.True(drop!.ContainsKey("id"));
        Assert.True(drop.ContainsKey("weight"));
    }

    [Fact]
    public void Execute_LookupFromValues_ReturnsFirstMatch()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?> { new Dictionary<string, object?>
            {
                ["id"] = "item", ["type"] = "lookup", ["source"] = "values", ["table"] = "items",
                ["where"] = new Dictionary<string, object?> { ["field"] = "id", ["op"] = "==", ["value"] = "sword" },
            } },
            ["response"] = new Dictionary<string, object?> { ["status"] = 200d, ["body"] = new Dictionary<string, object?> { ["name"] = "{{item.name}}" } },
        };
        var gameValues = new Dictionary<string, object?>
        {
            ["items"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "shield", ["name"] = "Shield" },
                new Dictionary<string, object?> { ["id"] = "sword", ["name"] = "Sword" },
            },
        };
        var request = new EndpointExecutionRequest(
            Input: new Dictionary<string, object?>(), SteamId: "s", PlayerKey: "s", GameValues: gameValues,
            ProjectId: "p", UserId: "u", HasSecretKey: false, IsDedicatedServer: false,
            ExecTime: FixedTime, ReadRecord: (_, _) => null);
        var result = executor.Execute(def, request);
        Assert.True(result.Ok);
        var body = (Dictionary<string, object?>)result.Body!;
        Assert.Equal("Sword", body["name"]);
    }

    [Fact]
    public void Execute_FilterFromValues_ReturnsMatchingItems()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?> { new Dictionary<string, object?>
            {
                ["id"] = "cheap", ["type"] = "filter", ["source"] = "values", ["table"] = "items",
                ["where"] = new Dictionary<string, object?> { ["field"] = "price", ["op"] = "<=", ["value"] = 50d },
            } },
            ["response"] = new Dictionary<string, object?> { ["status"] = 200d, ["body"] = new Dictionary<string, object?> { ["count"] = "{{cheap.length}}" } },
        };
        var gameValues = new Dictionary<string, object?>
        {
            ["items"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "potion", ["price"] = 10d },
                new Dictionary<string, object?> { ["id"] = "sword", ["price"] = 100d },
                new Dictionary<string, object?> { ["id"] = "shield", ["price"] = 50d },
            },
        };
        var request = new EndpointExecutionRequest(
            Input: new Dictionary<string, object?>(), SteamId: "s", PlayerKey: "s", GameValues: gameValues,
            ProjectId: "p", UserId: "u", HasSecretKey: false, IsDedicatedServer: false,
            ExecTime: FixedTime, ReadRecord: (_, _) => null);
        var result = executor.Execute(def, request);
        Assert.True(result.Ok);
        var body = (Dictionary<string, object?>)result.Body!;
        Assert.Equal(2d, body["count"]);
    }

    [Fact]
    public void Execute_LookupWithScanCollection_ReturnsFirstMatch()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?> { new Dictionary<string, object?>
            {
                ["id"] = "player", ["type"] = "lookup", ["collection"] = "players",
                ["where"] = new Dictionary<string, object?> { ["field"] = "name", ["op"] = "==", ["value"] = "cerbralone" },
            } },
            ["response"] = new Dictionary<string, object?> { ["status"] = 200d, ["body"] = new Dictionary<string, object?> { ["level"] = "{{player.totalLevel}}" } },
        };
        var scanData = new List<object?>
        {
            new Dictionary<string, object?> { ["name"] = "alice", ["totalLevel"] = 100d },
            new Dictionary<string, object?> { ["name"] = "cerbralone", ["totalLevel"] = 399d },
            new Dictionary<string, object?> { ["name"] = "bob", ["totalLevel"] = 50d },
        };
        var request = new EndpointExecutionRequest(
            Input: new Dictionary<string, object?>(), SteamId: "s", PlayerKey: "s", GameValues: new Dictionary<string, object?>(),
            ProjectId: "p", UserId: "u", HasSecretKey: false, IsDedicatedServer: false,
            ExecTime: FixedTime, ReadRecord: (_, _) => null,
            ScanCollection: (_) => scanData);
        var result = executor.Execute(def, request);
        Assert.True(result.Ok);
        var body = (Dictionary<string, object?>)result.Body!;
        Assert.Equal(399d, body["level"]);
    }

    [Fact]
    public void Execute_LookupNoMatch_ReturnsNull()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?> { new Dictionary<string, object?>
            {
                ["id"] = "player", ["type"] = "lookup", ["source"] = "values", ["table"] = "players",
                ["where"] = new Dictionary<string, object?> { ["field"] = "name", ["op"] = "==", ["value"] = "nonexistent" },
            } },
            ["response"] = new Dictionary<string, object?> { ["status"] = 200d, ["body"] = new Dictionary<string, object?> { ["found"] = "{{player | null}}" } },
        };
        var gameValues = new Dictionary<string, object?>
        {
            ["players"] = new List<object?> { new Dictionary<string, object?> { ["name"] = "alice" } },
        };
        var request = new EndpointExecutionRequest(
            Input: new Dictionary<string, object?>(), SteamId: "s", PlayerKey: "s", GameValues: gameValues,
            ProjectId: "p", UserId: "u", HasSecretKey: false, IsDedicatedServer: false,
            ExecTime: FixedTime, ReadRecord: (_, _) => null);
        var result = executor.Execute(def, request);
        Assert.True(result.Ok);
        var body = (Dictionary<string, object?>)result.Body!;
        Assert.Equal("null", EndpointExpression.JsToString(body["found"]));
    }

    private static EndpointExecutionRequest MinimalRequest() => new(
        Input: new Dictionary<string, object?>(),
        SteamId: "76561198000000000",
        PlayerKey: "76561198000000000",
        GameValues: new Dictionary<string, object?>(),
        ProjectId: "p", UserId: "u",
        HasSecretKey: false, IsDedicatedServer: false,
        ExecTime: FixedTime,
        ReadRecord: (_, _) => null);

    // ── Normalization: drop diagnostic error.step/error.docsUrl ──

    private static object? Normalize(object? body)
    {
        if (body is not Dictionary<string, object?> dict) return body;
        if (!dict.TryGetValue("error", out var errRaw) || errRaw is not Dictionary<string, object?> err) return body;
        var clone = new Dictionary<string, object?>(dict);
        var errClone = new Dictionary<string, object?>(err);
        errClone.Remove("step");
        errClone.Remove("docsUrl");
        clone["error"] = errClone;
        return clone;
    }

    // ── Oracle loading ──

    private sealed record OracleCase(string Id, JsonElement Def, JsonElement Request, bool Ok, int Status, JsonElement Body);

    private static OracleCase[] LoadOracle()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "NetworkStorage", "endpoint-executor-oracle.json");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        var list = new List<OracleCase>();
        foreach (var c in doc.RootElement.GetProperty("cases").EnumerateArray())
        {
            list.Add(new OracleCase(
                c.GetProperty("id").GetString()!,
                c.GetProperty("def").Clone(),
                c.GetProperty("request").Clone(),
                c.GetProperty("ok").GetBoolean(),
                c.GetProperty("status").GetInt32(),
                c.GetProperty("body").Clone()));
        }
        return list.ToArray();
    }

    private static object? ConvertJson(JsonElement el) => EndpointExpression.FromJson(el);

    private static Dictionary<string, object?> AsDict(object? v) => v as Dictionary<string, object?> ?? new Dictionary<string, object?>();

    private static string Json(object? v) => JsonSerializer.Serialize(v);

    private static bool JsDeepEquals(object? a, object? b)
    {
        if (EndpointExpression.IsNullish(a) || EndpointExpression.IsNullish(b))
            return EndpointExpression.IsNullish(a) && EndpointExpression.IsNullish(b);
        switch (a)
        {
            case double da when b is double db: return da == db || (double.IsNaN(da) && double.IsNaN(db));
            case bool ba when b is bool bb: return ba == bb;
            case string sa when b is string sb: return string.Equals(sa, sb, StringComparison.Ordinal);
            case List<object?> la when b is List<object?> lb:
                if (la.Count != lb.Count) return false;
                for (var i = 0; i < la.Count; i++) if (!JsDeepEquals(la[i], lb[i])) return false;
                return true;
            case Dictionary<string, object?> oa when b is Dictionary<string, object?> ob:
                if (oa.Count != ob.Count) return false;
                foreach (var (k, v) in oa) { if (!ob.TryGetValue(k, out var ov) || !JsDeepEquals(v, ov)) return false; }
                return true;
            default: return false;
        }
    }

    // ── Workflow step tests (async) ──

    [Fact]
    public async Task ExecuteAsync_WorkflowStep_LoadsAndExecutesSubSteps()
    {
        var executor = new EndpointStepExecutor();
        var workflowDef = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "greeting", ["type"] = "transform", ["value"] = "Hello World" },
            }
        };

        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "wf", ["type"] = "workflow", ["workflow"] = "greet-wf" },
            },
            ["response"] = new Dictionary<string, object?> { ["body"] = new Dictionary<string, object?> { ["greeting"] = "{{wf.greeting}}" } }
        };

        var request = MinimalRequestAsync(loadWorkflow: (_, _) => Task.FromResult<Dictionary<string, object?>?>(workflowDef));
        var result = await executor.ExecuteAsync(def, request);
        Assert.True(result.Ok, $"Expected Ok but got Status={result.Status} Body={Serialize(result.Body)}");
        var body = result.Body as Dictionary<string, object?>;
        Assert.NotNull(body);
        Assert.Equal("Hello World", body.GetValueOrDefault("greeting"));
    }

    [Fact]
    public async Task ExecuteAsync_WorkflowStep_ReturnsErrorOnFailure()
    {
        var executor = new EndpointStepExecutor();
        var workflowDef = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "must_fail", ["type"] = "assert",
                    ["check"] = new Dictionary<string, object?> { ["field"] = "input.x", ["op"] = "==", ["value"] = 99d } },
            }
        };

        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "wf", ["type"] = "workflow", ["workflow"] = "fail-wf" },
            }
        };

        var request = MinimalRequestAsync(loadWorkflow: (_, _) => Task.FromResult<Dictionary<string, object?>?>(workflowDef));
        var result = await executor.ExecuteAsync(def, request);
        Assert.False(result.Ok);
        Assert.Equal(400, result.Status);
    }

    [Fact]
    public async Task ExecuteAsync_WorkflowStep_NotFound_ReturnsError()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "wf", ["type"] = "workflow", ["workflow"] = "missing-wf" },
            }
        };

        var request = MinimalRequestAsync(loadWorkflow: (_, _) => Task.FromResult<Dictionary<string, object?>?>(null));
        var result = await executor.ExecuteAsync(def, request);
        Assert.False(result.Ok);
        Assert.Equal(400, result.Status);
    }

    // ── Routed flow tests (async) ──

    [Fact]
    public async Task ExecuteAsync_Condition_SkipRoute_SkipsNextStep()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?>
                {
                    ["id"] = "gate", ["type"] = "condition",
                    ["check"] = new Dictionary<string, object?> { ["field"] = "input.x", ["op"] = "==", ["value"] = 99d },
                    ["onFalse"] = new Dictionary<string, object?> { ["action"] = "skip", ["count"] = 1d }
                },
                new Dictionary<string, object?>
                {
                    ["id"] = "should_skip", ["type"] = "assert",
                    ["check"] = new Dictionary<string, object?> { ["field"] = "input.x", ["op"] = "==", ["value"] = 99d }
                },
            },
            ["response"] = new Dictionary<string, object?> { ["body"] = new Dictionary<string, object?> { ["ok"] = true } }
        };

        var result = await executor.ExecuteAsync(def, MinimalRequestAsync());
        Assert.True(result.Ok, $"Expected Ok but got Status={result.Status} Body={Serialize(result.Body)}");
    }

    [Fact]
    public async Task ExecuteAsync_Condition_ReturnRoute_ReturnsImmediately()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?>
                {
                    ["id"] = "gate", ["type"] = "condition",
                    ["check"] = new Dictionary<string, object?> { ["field"] = "input.x", ["op"] = "==", ["value"] = 1d },
                    ["onTrue"] = "return"
                },
                new Dictionary<string, object?>
                {
                    ["id"] = "should_not_run", ["type"] = "assert",
                    ["check"] = new Dictionary<string, object?> { ["field"] = "input.x", ["op"] = "==", ["value"] = 99d }
                },
            },
            ["response"] = new Dictionary<string, object?> { ["body"] = new Dictionary<string, object?> { ["ok"] = true } }
        };

        var request = MinimalRequestAsync(input: new Dictionary<string, object?> { ["x"] = 1d });
        var result = await executor.ExecuteAsync(def, request);
        Assert.True(result.Ok, $"Expected Ok but got Status={result.Status} Body={Serialize(result.Body)}");
    }

    [Fact]
    public async Task ExecuteAsync_Condition_GotoRoute_JumpsToTarget()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?>
                {
                    ["id"] = "gate", ["type"] = "condition",
                    ["check"] = new Dictionary<string, object?> { ["field"] = "input.x", ["op"] = "==", ["value"] = 99d },
                    ["onFalse"] = new Dictionary<string, object?> { ["action"] = "goto", ["step"] = "target" }
                },
                new Dictionary<string, object?>
                {
                    ["id"] = "should_skip", ["type"] = "assert",
                    ["check"] = new Dictionary<string, object?> { ["field"] = "input.x", ["op"] = "==", ["value"] = 99d }
                },
                new Dictionary<string, object?> { ["id"] = "target", ["type"] = "transform", ["value"] = "reached" },
            },
            ["response"] = new Dictionary<string, object?> { ["body"] = new Dictionary<string, object?> { ["result"] = "{{target}}" } }
        };

        var result = await executor.ExecuteAsync(def, MinimalRequestAsync());
        Assert.True(result.Ok, $"Expected Ok but got Status={result.Status} Body={Serialize(result.Body)}");
        var body = result.Body as Dictionary<string, object?>;
        Assert.NotNull(body);
        Assert.Equal("reached", body.GetValueOrDefault("result"));
    }

    [Fact]
    public async Task ExecuteAsync_Condition_RunRoute_ExecutesSubWorkflow()
    {
        var executor = new EndpointStepExecutor();
        var subWorkflow = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "sub_result", ["type"] = "transform", ["value"] = "from-workflow" },
            }
        };

        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?>
                {
                    ["id"] = "gate", ["type"] = "condition",
                    ["check"] = new Dictionary<string, object?> { ["field"] = "input.x", ["op"] = "==", ["value"] = 99d },
                    ["onFalse"] = new Dictionary<string, object?> { ["action"] = "run", ["flow"] = "sub-wf" }
                },
            },
            ["response"] = new Dictionary<string, object?> { ["body"] = new Dictionary<string, object?> { ["ok"] = true } }
        };

        var request = MinimalRequestAsync(loadWorkflow: (_, _) => Task.FromResult<Dictionary<string, object?>?>(subWorkflow));
        var result = await executor.ExecuteAsync(def, request);
        Assert.True(result.Ok, $"Expected Ok but got Status={result.Status} Body={Serialize(result.Body)}");
    }

    // ── Webhook + sleep tests ──

    [Fact]
    public async Task ExecuteAsync_WebhookStep_SkipsInDryRunMode()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "x", ["type"] = "transform", ["value"] = 1d },
                new Dictionary<string, object?>
                {
                    ["id"] = "wh", ["type"] = "webhook",
                    ["url"] = "https://discord.com/api/webhooks/123/abc",
                    ["title"] = "Test", ["description"] = "Hello"
                },
            },
            ["response"] = new Dictionary<string, object?> { ["body"] = new Dictionary<string, object?> { ["ok"] = true } }
        };

        var sent = false;
        var request = MinimalRequestAsync(
            skipWebhooks: true,
            executeWebhook: (_, _, _) => { sent = true; return Task.FromResult((true, 204, (string?)null)); });
        var result = await executor.ExecuteAsync(def, request);
        Assert.True(result.Ok, $"Expected Ok but got Status={result.Status} Body={Serialize(result.Body)}");
        Assert.False(sent, "Dry-run mode (_skipWebhooks) must NOT invoke the real webhook sender");
    }

    [Fact]
    public async Task ExecuteAsync_WebhookStep_SendsWhenNotDryRun()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?>
                {
                    ["id"] = "wh", ["type"] = "webhook",
                    ["url"] = "https://discord.com/api/webhooks/123/abc",
                    ["title"] = "Test", ["description"] = "Hello"
                },
            },
            ["response"] = new Dictionary<string, object?> { ["body"] = new Dictionary<string, object?> { ["ok"] = true } }
        };

        string? sentUrl = null;
        var request = MinimalRequestAsync(
            skipWebhooks: false,
            executeWebhook: (url, _, _) => { sentUrl = url; return Task.FromResult((true, 204, (string?)null)); });
        var result = await executor.ExecuteAsync(def, request);
        Assert.True(result.Ok, $"Expected Ok but got Status={result.Status} Body={Serialize(result.Body)}");
        Assert.Equal("https://discord.com/api/webhooks/123/abc", sentUrl);
    }

    [Fact]
    public async Task ExecuteAsync_WebhookStep_InvalidUrl_ReturnsError()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?>
                {
                    ["id"] = "wh", ["type"] = "webhook",
                    ["url"] = "https://example.com/not-discord",
                    ["title"] = "Test"
                },
            }
        };

        var result = await executor.ExecuteAsync(def, MinimalRequestAsync());
        Assert.False(result.Ok, "Expected failure for non-Discord URL");
        Assert.Equal(400, result.Status);
    }

    [Fact]
    public async Task ExecuteAsync_SleepStep_ZeroDuration_CompletesImmediately()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "s", ["type"] = "sleep", ["durationMs"] = 0d },
            },
            ["response"] = new Dictionary<string, object?> { ["body"] = new Dictionary<string, object?> { ["ok"] = true } }
        };

        var result = await executor.ExecuteAsync(def, MinimalRequestAsync());
        Assert.True(result.Ok);
    }

    [Fact]
    public async Task ExecuteAsync_SleepStep_NegativeDuration_ReturnsError()
    {
        var executor = new EndpointStepExecutor();
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "s", ["type"] = "sleep", ["durationMs"] = -1d },
            }
        };

        var result = await executor.ExecuteAsync(def, MinimalRequestAsync());
        Assert.False(result.Ok);
        Assert.Equal(400, result.Status);
    }
    // ── Native-serve webhook-sender requirement (RequiresLiveWebhookSender) ──

    [Theory]
    [InlineData("webhook")]
    [InlineData("workflow")]
    public void RequiresLiveWebhookSender_DetectsWebhookCapableStep(string stepType)
    {
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "r", ["type"] = "read", ["collection"] = "c" },
                new Dictionary<string, object?> { ["id"] = "x", ["type"] = stepType },
            }
        };
        Assert.True(EndpointStepExecutor.RequiresLiveWebhookSender(def));
    }

    [Theory]
    [InlineData("write")]
    [InlineData("delete")]
    public void RequiresLiveWebhookSender_RecordMutationStep_IsSafe(string stepType)
    {
        // Writes/deletes are flushed durably by the live-serve path, so they no longer
        // force a Bun fallback — only a potential webhook does.
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "r", ["type"] = "read", ["collection"] = "c" },
                new Dictionary<string, object?> { ["id"] = "x", ["type"] = stepType, ["collection"] = "c" },
            }
        };
        Assert.False(EndpointStepExecutor.RequiresLiveWebhookSender(def));
    }

    [Fact]
    public void RequiresLiveWebhookSender_DetectsNestedWebhookInsideBlock()
    {
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?>
                {
                    ["id"] = "b", ["type"] = "block",
                    ["steps"] = new List<object?>
                    {
                        new Dictionary<string, object?> { ["id"] = "n", ["type"] = "webhook" }
                    }
                }
            }
        };
        Assert.True(EndpointStepExecutor.RequiresLiveWebhookSender(def));
    }

    [Fact]
    public void RequiresLiveWebhookSender_NestedWriteInsideBlock_IsSafe()
    {
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?>
                {
                    ["id"] = "b", ["type"] = "block",
                    ["steps"] = new List<object?>
                    {
                        new Dictionary<string, object?> { ["id"] = "w", ["type"] = "write", ["collection"] = "c" }
                    }
                }
            }
        };
        Assert.False(EndpointStepExecutor.RequiresLiveWebhookSender(def));
    }

    [Fact]
    public void RequiresLiveWebhookSender_DetectsWorkflowReferenceOnCondition()
    {
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "c", ["type"] = "condition", ["workflow"] = "wf123" }
            }
        };
        Assert.True(EndpointStepExecutor.RequiresLiveWebhookSender(def));
    }

    [Fact]
    public void RequiresLiveWebhookSender_ReadOnlyEndpoint_IsSafe()
    {
        var def = new Dictionary<string, object?>
        {
            ["steps"] = new List<object?>
            {
                new Dictionary<string, object?> { ["id"] = "r", ["type"] = "read", ["collection"] = "c" },
                new Dictionary<string, object?> { ["id"] = "t", ["type"] = "transform", ["value"] = 1d },
                new Dictionary<string, object?> { ["id"] = "lb", ["type"] = "lookup", ["collection"] = "c2" },
            },
            ["response"] = new Dictionary<string, object?> { ["body"] = new Dictionary<string, object?> { ["ok"] = true } }
        };
        Assert.False(EndpointStepExecutor.RequiresLiveWebhookSender(def));
    }

    // ── Async test helpers ──

    private static EndpointExecutionRequest MinimalRequestAsync(
        IReadOnlyDictionary<string, object?>? input = null,
        Func<string, CancellationToken, Task<Dictionary<string, object?>?>>? loadWorkflow = null,
        bool skipWebhooks = false,
        Func<string, Dictionary<string, object?>, CancellationToken, Task<(bool Ok, int Status, string? Error)>>? executeWebhook = null) => new(
        Input: input ?? new Dictionary<string, object?>(),
        SteamId: "76561198000000000",
        PlayerKey: "76561198000000000",
        GameValues: new Dictionary<string, object?>(),
        ProjectId: "p", UserId: "u",
        HasSecretKey: false, IsDedicatedServer: false,
        ExecTime: FixedTime,
        ReadRecord: (_, _) => null,
        LoadWorkflow: loadWorkflow,
        ExecuteWebhookAsync: executeWebhook,
        SkipWebhooks: skipWebhooks);

    private static string Serialize(object? v) => JsonSerializer.Serialize(v);
}
